'use strict';
const $=s=>document.querySelector(s),B=window.BidMonitor;
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai'}).format(new Date());
$('#startDate').value=$('#endDate').value=today();
let raw=[],analyzed=[],visible=[],page=1,range=null,source='',busy=false,abort;
const names={'missing':'字段缺失/非数值','no-register':'无注册，暂不判断','no-return':'无回传，暂不判断','abnormal':'回传超过 100%，核对口径','sample':'样本不足','pending':'当日待回补，暂不调价','loss-bid':'出价超过理论保本线','margin-bid':'出价未达目标毛利','within':'出价在理论上限内'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>v===null||v===undefined?'--':Number(v).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
function message(text,bad=false){$('#message').textContent=text;$('#message').className=bad?'error':''}
async function api(path,options={}){const response=await fetch(path,options);if(response.status===401){location.replace('/login');throw Error('请先登录')}const text=await response.text();let data;try{data=JSON.parse(text)}catch{throw Error(`接口 HTTP ${response.status}，未返回 JSON，请确认后端已经部署`)}if(!response.ok)throw Error(data.error||data.message||`HTTP ${response.status}`);return data}
function setBusy(value){busy=value;$('#fetch').disabled=$('#import').disabled=value;$('#cancel').disabled=!value}
function dates(){const start=$('#startDate').value,end=$('#endDate').value;if(!start||!end||start>end)throw Error('请选择有效的统计日期范围');return{start,end}}
function receive(rows,label,datesValue){if(!rows.length)throw Error('返回 0 条计划，保留原有结果');const next=rows.map(B.normalize);if(!next.some(r=>r.cost!==null&&r.registrations!==null&&r.conversions!==null&&r.bid!==null))throw Error('未识别到消耗、转化数、注册数和出价四个字段，请核对报表表头或提供脱敏接口响应');raw=next;range=datesValue;source=label;page=1;render();message(`已读取 ${raw.length} 条计划${$('#price').value?'':'，请填写客户结算单价'}`)}
function render(){
 const price=Number($('#price').value),margin=Number($('#margin').value),sample=Number($('#minSample').value);
 $('#source').textContent=range?`${source} · 统计区间 ${range.start} 至 ${range.end} · ${raw.length} 条计划（元）`:'尚未查询或导入数据';
 const current=range?range.end>=today():true;$('#lag').hidden=!current;
 if(!(price>0)||!Number.isFinite(price)||!Number.isFinite(margin)||margin<0||margin>=100||!Number.isInteger(sample)||sample<1){analyzed=[];visible=[];$('#metrics').textContent='请填写有效结算价、毛利率和样本阈值';$('#rows').innerHTML='<tr><td class="empty" colspan="12">填写客户结算单价后生成判断</td></tr>';$('#export').disabled=true;$('#prev').disabled=$('#next').disabled=true;return}
 analyzed=raw.map(r=>B.analyze(r,price,margin,sample,current));
 const sum=key=>raw.reduce((n,r)=>n+(r[key]??0),0),complete=key=>raw.length&&raw.every(r=>r[key]!==null);
 const cost=complete('cost')?sum('cost'):null,reg=complete('registrations')?sum('registrations'):null,conv=complete('conversions')?sum('conversions'):null;
 $('#metrics').innerHTML=[['总消耗',fmt(cost)],['注册数',reg??'--'],['转化数',conv??'--'],['整体回传比例',reg>0&&conv!==null?fmt(conv/reg*100)+'%':'--'],['估算利润',cost!==null&&reg!==null?fmt(reg*price-cost):'--']].map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${esc(v)}</strong></div>`).join('');
 const q=$('#search').value.trim().toLowerCase(),filter=$('#filter').value,key=$('#sort').value;
 visible=analyzed.filter(r=>(!q||[r.id,r.name,r.account,r.accountId].join(' ').toLowerCase().includes(q))&&(filter==='all'||r.status===filter)).sort((a,b)=>(b[key]??-Infinity)-(a[key]??-Infinity));
 const size=Number($('#pageSize').value),pages=Math.max(1,Math.ceil(visible.length/size));page=Math.min(page,pages);
 $('#rows').innerHTML=visible.slice((page-1)*size,page*size).map(r=>`<tr><td>${esc(r.name||'未命名计划')}<small>${esc(r.id)}</small></td><td>${esc(r.account||r.accountId||'--')}<small>${esc(r.account?r.accountId:'')}</small></td>${[r.cost,r.conversions,r.registrations].map(v=>`<td>${fmt(v)}</td>`).join('')}<td>${r.ratio===null?'--':fmt(r.ratio*100)+'%'}</td><td>${fmt(r.bid)}</td><td>${fmt(r.cpa)}</td><td>${fmt(r.breakEven)}</td><td>${fmt(r.ceiling)}</td><td class="${r.profit<0?'bad':'good'}">${fmt(r.profit)}</td><td class="${r.status==='loss-bid'?'bad':r.status==='within'?'good':'warn'}">${esc(names[r.status])}</td></tr>`).join('')||'<tr><td colspan="12" class="empty">没有符合条件的计划</td></tr>';
 $('#count').textContent=`${visible.length} 条`;$('#pageLabel').textContent=`第 ${page} / ${pages} 页`;$('#prev').disabled=page<=1;$('#next').disabled=page>=pages;$('#export').disabled=!visible.length;
}
$('#fetch').onclick=async()=>{if(busy)return;setBusy(true);abort=new AbortController();try{const selected=dates(),payload={startDate:selected.start,endDate:selected.end,cookie:$('#cookie').value.trim(),clientUser:$('#clientUser').value.trim(),mainUserId:$('#mainUserId').value.trim(),createdStart:$('#createdStart').value,createdEnd:$('#createdEnd').value};if(!payload.cookie)throw Error('请展开接口凭据并填写 Cookie');let all=[],total=null,finished=false;for(let p=1;p<=200;p++){message(`正在读取第 ${p} 页，已读取 ${all.length} 条`);const data=await api('/api/bid-monitor/page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,page:p}),signal:abort.signal});if(!Array.isArray(data.rows))throw Error('接口列表格式异常');if(data.total!==null&&data.total!==undefined){const n=Number(data.total);if(!Number.isInteger(n)||n<0)throw Error('接口总条数异常');if(total!==null&&total!==n)throw Error('分页期间计划总数变化，请重试');total=n}all.push(...data.rows);if(!data.rows.length||data.rows.length<100||(total!==null&&all.length>=total)){finished=true;break}}if(!finished)throw Error('超过 200 页，请缩小日期范围或添加计划创建日期限制');if(total!==null&&all.length!==total)throw Error(`分页不完整，应有 ${total} 条，实际 ${all.length} 条，保留原有结果`);const ids=new Set();for(const row of all){const r=B.normalize(row),key=r.id?`${r.accountId}:${r.id}`:'';if(key&&ids.has(key))throw Error('分页出现重复计划，可能因消耗排序变化，请重试或使用导出报表');if(key)ids.add(key)}receive(all,'创量查询 '+new Date().toLocaleTimeString('zh-CN'),selected)}catch(error){message(error.name==='AbortError'?'已取消查询，原结果未改变':error.message,true)}finally{setBusy(false)}};
$('#cancel').onclick=()=>abort?.abort();$('#import').onclick=()=>$('#file').click();
$('#file').onchange=async()=>{if(!$('#file').files.length||busy)return;setBusy(true);try{const selected=dates(),file=$('#file').files[0],form=new FormData();form.append('file',file);message('正在读取 Excel…');const data=await api('/api/bid-monitor/import',{method:'POST',body:form});receive(data.rows,`导入 ${file.name}`,selected)}catch(error){message(error.message,true)}finally{$('#file').value='';setBusy(false)}};
for(const id of ['price','margin','minSample','search','filter','sort','pageSize'])$('#'+id).addEventListener('input',()=>{page=1;render()});
for(const id of ['startDate','endDate'])$('#'+id).onchange=()=>{if(raw.length)message('日期已修改，请重新查询或导入对应日期的报表；下方仍为原统计区间数据')};
$('#prev').onclick=()=>{page--;render()};$('#next').onclick=()=>{page++;render()};
$('#export').onclick=()=>{const cell=v=>'"'+String(v??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const rows=[['计划ID','计划名称','账户','统计开始','统计结束','消耗','转化数','注册数','回传比例','当前出价','注册成本','理论保本价','目标出价上限','估算利润','判断'],...visible.map(r=>[r.id,r.name,r.account||r.accountId,range.start,range.end,r.cost,r.conversions,r.registrations,r.ratio,r.bid,r.cpa,r.breakEven,r.ceiling,r.profit,names[r.status]])];const url=URL.createObjectURL(new Blob(['\ufeff'+rows.map(row=>row.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`出价监测_${range.start}_${range.end}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
(async()=>{try{const session=await api('/api/session');if(!session.authenticated){location.replace('/login');return}const permissions=await api('/api/tool-visibility');if(permissions.bidMonitor!==true){location.replace('/tools');return}document.body.classList.add('ready');render()}catch(error){document.body.classList.add('ready');message(error.message,true)}})();
