spring.application.name=marketing-reports
server.address=${DHH_HOST:127.0.0.1}
server.port=${DHH_PORT:8765}
server.forward-headers-strategy=framework
spring.jackson.default-property-inclusion=always
spring.mvc.async.request-timeout=35000
logging.level.root=INFO
