ALTER TABLE `report_sync_runs`
  COMMENT = '报表手动更新与每日定时同步执行记录',
  MODIFY `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '同步任务自增主键',
  MODIFY `report_type` ENUM('dhh', 'jd', 'all') NOT NULL COMMENT '报表类型：dhh大航海、jd京东、all全部',
  MODIFY `trigger_type` ENUM('manual', 'scheduled') NOT NULL COMMENT '触发方式：manual手动、scheduled定时',
  MODIFY `status` ENUM('running', 'success', 'failed') NOT NULL DEFAULT 'running' COMMENT '同步状态：运行中、成功、失败',
  MODIFY `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '同步开始时间',
  MODIFY `finished_at` DATETIME(3) NULL COMMENT '同步完成时间',
  MODIFY `row_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '本次同步写入或更新的底表行数',
  MODIFY `error_message` VARCHAR(1000) NULL COMMENT '同步失败原因，成功时为空';

ALTER TABLE `dhh_daily_rows`
  COMMENT = '大航海日报原始底表数据',
  MODIFY `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '大航海底表自增主键',
  MODIFY `business_date` DATE NOT NULL COMMENT '业务日期，北京时间，格式YYYY-MM-DD',
  MODIFY `media` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '投放媒体名称',
  MODIFY `optimizer` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '优化师姓名',
  MODIFY `project_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '项目名称，由任务名称归类',
  MODIFY `task_name` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '原始日报任务名称',
  MODIFY `account_info` JSON NULL COMMENT '媒体账户明细JSON，包含账户ID、名称及账户消耗',
  MODIFY `spend` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '总消耗，单位：元',
  MODIFY `cash_spend` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '现金消耗，单位：元',
  MODIFY `reward_spend` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '赠款消耗，单位：元',
  MODIFY `estimated_commission` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '预估佣金，单位：元',
  MODIFY `settlement_count` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '结算数量',
  MODIFY `conversion_count` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '转化数量',
  MODIFY `registration_count` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '注册数量',
  MODIFY `row_hash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原始行SHA-256哈希，用于防止重复写入',
  MODIFY `synced_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最近一次同步写入时间';

ALTER TABLE `jd_daily_rows`
  COMMENT = '京东CPA日报原始底表数据',
  MODIFY `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '京东底表自增主键',
  MODIFY `business_date` DATE NOT NULL COMMENT '业务日期，北京时间，格式YYYY-MM-DD',
  MODIFY `promotion_id` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '推广位ID',
  MODIFY `promotion_name` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '推广位名称',
  MODIFY `media` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '投放媒体名称',
  MODIFY `media_account_id` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '媒体账户ID',
  MODIFY `media_account_name` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '媒体账户名称',
  MODIFY `promoter_username` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '推客用户名',
  MODIFY `optimizer` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '优化师姓名',
  MODIFY `conversion_count` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '转化数量',
  MODIFY `billable_conversion_count` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '计费转化数量',
  MODIFY `deduplicated_order_count` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '去重订单总数',
  MODIFY `first_purchase_order_count` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '首购订单总数',
  MODIFY `return_order_count` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '回流订单总数',
  MODIFY `first_purchase_effective_orders` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '首购有效订单数',
  MODIFY `return_effective_orders` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '回流有效订单数',
  MODIFY `first_purchase_invalid_orders` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '首购无效订单数',
  MODIFY `return_invalid_orders` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '回流无效订单数',
  MODIFY `first_purchase_completed_orders` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '首购已完成订单数',
  MODIFY `return_completed_orders` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '回流已完成订单数',
  MODIFY `spend` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '总消耗，单位：元',
  MODIFY `estimated_compensation` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '条件内预估赔付金额（当日），单位：元',
  MODIFY `first_purchase_estimated_commission` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '首购预估佣金，单位：元',
  MODIFY `return_estimated_commission` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '回流预估佣金，单位：元',
  MODIFY `first_purchase_actual_commission` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '首购实际佣金，单位：元',
  MODIFY `return_actual_commission` DECIMAL(18, 2) NOT NULL DEFAULT 0 COMMENT '回流实际佣金，单位：元',
  MODIFY `row_hash` CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '原始行SHA-256哈希，用于防止重复写入',
  MODIFY `synced_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
    ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '最近一次同步写入时间';
