const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
(async()=>{const root=path.resolve(__dirname,'../frontend'),server=http.createServer((req,res)=>{const file=path.join(root,path.basename(new URL(req.url,'http://localhost').pathname));if(!fs.existsSync(file)||!fs.statSync(file).isFile()){res.writeHead(404).end();return;}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html;charset=utf-8');res.end(fs.readFileSync(file));});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
try{browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());await page.route('**/pet-loader.js*',r=>r.fulfill({body:''}));await page.route('**/api/**',r=>r.fulfill({json:new URL(r.request().url()).pathname==='/api/session'?{authenticated:true,user:{id:1,role:'member'}}:{}}));
await page.goto(`http://127.0.0.1:${server.address().port}/games.html`);await page.locator('[data-game="go"]').click();await page.locator('#goBoard button').first().waitFor();assert.equal(await page.locator('#goBoard button').count(),81);
const cell=i=>page.locator(`#goBoard [data-index="${i}"]`);await cell(1).click();await cell(0).click();await cell(9).click();assert.equal(await cell(0).getAttribute('data-player'),'0');assert.match(await page.locator('#goCaptures').textContent(),/黑方提子 1/);await cell(0).click();assert.match(await page.locator('#goNotice').textContent(),/自杀/);await page.locator('#goUndo').click();assert.equal(await cell(0).getAttribute('data-player'),'2');
await page.locator('#goPass').click();await page.locator('#goPass').click();assert.equal(await page.locator('#goScoring').isVisible(),true);await cell(0).click();assert.match(await cell(0).getAttribute('class'),/dead/);await page.locator('#goResume').click();assert.equal(await page.locator('.dead').count(),0);await page.locator('#goPass').click();await page.locator('#goPass').click();await page.locator('#goFinish').click();assert.match(await page.locator('#goStatus').textContent(),/胜|平局/);assert.equal(await page.locator('#goPass').isDisabled(),true);
await page.locator('#goSize').selectOption('19');assert.equal(await page.locator('#goBoard button').count(),361);await cell(180).focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');assert.equal(await cell(181).getAttribute('data-player'),'1');
fs.mkdirSync(path.resolve(__dirname,'../.runtime'),{recursive:true});await page.screenshot({path:path.resolve(__dirname,'../.runtime/go-desktop.png')});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.resolve(__dirname,'../.runtime/go-mobile.png')});assert.deepEqual(errors,[]);console.log('PASS Go UI: lobby, capture, invalid move, undo, scoring, dead stones, resume, finish, resize, keyboard, mobile');
}finally{await browser?.close();await new Promise(resolve=>server.close(resolve));}})().catch(e=>{console.error(e);process.exitCode=1;});
